### ISSUE TITLE
Add Breeze Mode support.

### ISSUE THREAD

**Issue by garrett3333** [wonderslug/aiomodernforms#88]
Thanks for the awesome work writing this code and integrating Modern Forms controls with Home Assistant! (I think you were behind that)

There's a feature on the Modern Forms DC powered fans, if you press and hold the "reverse" button on your fan remote, the fan enters "Breeze Mode" and the speed of the fan starts to vary with time, making the airflow feel like a light breeze. It's surprisingly nice. I'm wondering if you came across this at all and if there's a way to toggle breeze mode on and off using your python code, and/or home assistant. Do you know?

**Comment by wonderslug** [comment]
Hey there,

You're welcome, need it myself. 

Its been talked about (https://community.home-assistant.io/t/modern-forms-add-additional-modes-breeze-mode/343140). But the Fan and Controller that I have does not have Breeze mode.  The phone app shows it and it should be able to be done if we can find the right network call to the fan.  Its not really documented anywhere.

If you happen to have a way to capture network traffic between the phone app and the fan im sure we could figure it out and add it.

**Comment by garrett3333** [comment]
Not a developer and not super well versed on network comms but I think I just made that happen...

Turned on breeze mode and found the following sent to the fan IP...

  **_{"wind":true,"windSpeed":"2","fanOn":true}_**

It looks like "windSpeed" can be either 1, 2 or 3.

Turned off breeze mode and found the following

  **_{"wind":false}_**

Does that make sense in the context of the other controls? Or do I need to trace more of the communication before and after this?

**Comment by wonderslug** [comment]
thats pretty great!   That helps a lot.  I would like to get a bit more info if possible.  

If you happen to have curl on your command line could you please run the following queries on the fan and give me the outputs:

`curl --location --request POST 'http://<ip_address_of_your_fan>:80/mf' --header 'Content-Type: application/json' --data-raw '{"queryDynamicShadowData": 1}'`

`curl --location --request POST 'http://<ip_address_of_your_fan>:80/mf' --header 'Content-Type: application/json' --data-raw '{"queryStaticShadowData": 1}'`

**Comment by garrett3333** [comment]
Here's the first request response, I definitely redacted some of the values but I don't think that'll matter.

{
"clientId":"MF_<fanID>",
"cloudPort":####,
"lightOn":false,
"fanOn":false,
"lightBrightness":100,
"fanSpeed":3,
"fanDirection":"forward",
"wind":true,
"windSpeed":1,
"rfPairModeActive":false,
"resetRfPairList":false,
"factoryReset":false,
"awayModeEnabled":false,
"fanTimer":0,
"lightTimer":0,
"decommission":false,
"schedule":"",
"adaptiveLearning":false,
"userData":"local_wifi",
"timezone":"UTC+0x:xx",
"FrCodes":"xxxxxxxxxxxxxxxx"
}

{
"clientId":"MF_<fanID>",
"mac":"<mac address>",
"lightType":"F4IN-120V-R1-30",
"fanType":"1801-60",
"fanMotorType":"DC125X30",
"brand":1,
"dateCode":"<date>",
"owner":"myemail@gmail.com",
"federatedIdentity":"us-east-<garbaldygoop>",
"deviceName":"MYFAN",
"firmwareVersion":"02.00.0026",
"mainMcuFirmwareVersion":"03.00.0000",
"firmwareUrl":"",
"wifiSignal":"-36",
"SSID":"<MYSSID>",
"BSSID":"<MYBSSID>",
"isUvcFan":false
}

**Comment by wonderslug** [comment]
Perfect.  Thank you.   Ill try to see if I can get this added to the lib and then to HA.

**Comment by lurgh** [comment]
It's been a while since this was merged but I see you never cut a release to pick it up, nor presumably got back to the HA integration.  I'd be interested in completing the work.  

Can you confirm whether this Breeze Mode code was ever tested on a real fan?  If so would you be willing to cut a 0.2.0 release or whatever so I can hopefully avoid forking this project?

Anything to share that got started on the HA side?

Thanks

**Comment by kylepet** [comment]
I just set up a modern forms fan that supports breeze mode. I played around and commands like `url --location --request POST 'http://<Fan IP>:80/mf' --header 'Content-Type: application/json' --data-raw '{"wind": true, "windSpeed": 1}'` work. I then downloaded the latest version of this package and installed it, and then tried this example script:
```
"""Asynchronous Python client for Async IO Modern Forms fan."""
import asyncio
from datetime import datetime, timedelta

import aiomodernforms
from aiomodernforms.const import LIGHT_POWER_OFF, LIGHT_POWER_ON, WIND_ON, WIND_OFF


async def main():
    """Turn on the fan light."""
    async with aiomodernforms.ModernFormsDevice("<Fan IP>") as fan:
        await fan.update()
        print(fan.status)
        await fan.fan(
            wind = WIND_ON,
            wind_speed = 1,
        )

        print(fan.status)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

And looking at my phone running the modern forms app I was able to see it successfully toggle breeze mode as well as change the breeze mode speeds. The regular fan speed is from 1 to 6 and breeze mode is 1 to 3. These speeds are set separately and toggling breeze mode switches between the two scales. I don't have any experience with home assistant so I'm not sure how this would be implemented since the fan speed percentages are locked to 1/6 intervals and that would need to be changed and reflect in other bridged apps like HomeKit. Getting this integrated into home assistant would be really cool, so hopefully a version `0.2.0` of this package can be released! I'd be happy to test anything on my end or try and implement it once this package is updated.
